"""Report-structure normalization and invariant repair helpers.

These functions are deliberately pure text/rule utilities. The orchestrator
uses them during report generation, while tests can exercise them without
instantiating a full pipeline.
"""
from __future__ import annotations

import re
from typing import Iterable

from schemas import Insight, Verdict


def _extract_cited_ids(text: str) -> set[int]:
    """Extract body citation ids from Markdown text.

    GFM footnote definition lines such as ``[^1]: source`` are not counted as
    body citations.
    """
    ids: set[int] = set()
    if not text:
        return ids
    for line in (text or "").split("\n"):
        stripped = line.strip()
        if re.match(r"^\[\^\d{1,3}\]:", stripped):
            continue
        for m in re.finditer(r"\[\^?(\d{1,3})\]", line):
            try:
                ids.add(int(m.group(1)))
            except ValueError:
                pass
    return ids


_NARRATIVE_STRIP_SECTIONS = {
    "终审备注", "终审自检", "自检备注", "研究方法与数据说明", "分析方法说明",
    "参考文献", "References", "参考来源", "资料来源", "数据来源",
}
_FACTS_SECTION_ALIASES = ("基本事实", "行业格局", "公司画像", "公司概况", "行业概况", "公司与行业概况")
_HISTORY_SECTION_ALIASES = ("历史趋势", "历史趋势与拐点", "趋势与拐点", "发展历程")
_SINGLETON_H2_ALIASES = ("执行摘要", "基本事实", "行业格局", "公司画像", "公司概况", "行业概况", "公司与行业概况")
_SINGLETON_H3_ALIASES = ("历史趋势", "历史趋势与拐点", "趋势与拐点", "发展历程", "财务概览", "估值与融资概览")


def _strip_llm_references(body: str) -> str:
    """Remove reference sections generated by the LLM itself.

    The code-generated appendix uses ``### 参考文献`` plus markdown list rows,
    so this only strips footnote-definition residue and non-heading reference
    title fragments.
    """
    if not body:
        return body
    result: list[str] = []
    for line in body.split("\n"):
        stripped = line.strip()
        if re.match(r"^\[\^\d{1,3}\]:", stripped):
            continue
        if (
            not stripped.startswith("#")
            and (
                any(kw in stripped for kw in ("参考文献", "参考来源", "资料来源", "数据来源", "引用文献"))
                or re.search(r"引用\s*\d+\s*条", stripped)
            )
        ):
            continue
        result.append(line)
    return "\n".join(result)


def strip_generated_report_tail(body: str) -> str:
    """Remove a previously code-generated appendix/footer before reprocessing.

    This makes offline evaluation reprocessing idempotent.  Normal report
    generation does not need it because it starts from a fresh model body.
    """
    if not body:
        return body
    lines = body.splitlines()
    cut = len(lines)
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if re.match(
            r"^#{3,6}\s*(?:数据缺口|参考文献)(?:\s|（|\(|$)",
            stripped,
        ):
            cut = idx
            break
        if (
            stripped == "---"
            and idx + 1 < len(lines)
            and lines[idx + 1].strip().startswith("数据截至 ")
        ):
            cut = idx
            break
    return "\n".join(lines[:cut]).rstrip()


def _heading_level(line: str) -> int:
    m = re.match(r"^(#{1,6})\s+", line or "")
    return len(m.group(1)) if m else 0


def _heading_key(line: str) -> str:
    title = re.sub(r"^#{1,6}\s*", "", line or "").strip()
    title = re.sub(r"^\d+(?:[.、]\d+)*[.、]?\s*", "", title).strip()
    title = re.sub(r"\s+", "", title)
    for alias in sorted(set(_SINGLETON_H2_ALIASES + _SINGLETON_H3_ALIASES), key=len, reverse=True):
        if alias in title:
            return alias
    return title


def _dedupe_report_sections(body: str) -> str:
    """Remove duplicate report structure blocks after LLM retries/polish."""
    lines = (body or "").splitlines()
    blocks: list[tuple[int, str, list[str]]] = []
    cur_level = 0
    cur_key = ""
    cur_lines: list[str] = []
    for line in lines:
        level = _heading_level(line)
        if level in (2, 3):
            if cur_lines:
                blocks.append((cur_level, cur_key, cur_lines))
            cur_level = level
            cur_key = _heading_key(line)
            cur_lines = [line]
        else:
            cur_lines.append(line)
    if cur_lines:
        blocks.append((cur_level, cur_key, cur_lines))

    seen_h2: set[str] = set()
    seen_h3: set[str] = set()
    kept: list[str] = []
    for level, key, block in blocks:
        if level == 2 and key in _SINGLETON_H2_ALIASES:
            if key in seen_h2:
                continue
            seen_h2.add(key)
        if level == 3 and key in _SINGLETON_H3_ALIASES:
            if key in seen_h3:
                continue
            seen_h3.add(key)
        kept.extend(block)
    return "\n".join(kept).strip()


def _merge_history_to_facts(body: str) -> str:
    """Move a standalone history section under the facts section."""
    if not body:
        return body
    lines = body.split("\n")
    sections: list[tuple[int, str, list[str]]] = []
    cur_level = 0
    cur_title = ""
    cur_lines: list[str] = []
    for line in lines:
        m2 = re.match(r"^(##)\s+(.+)$", line.strip())
        m3 = re.match(r"^(###)\s+(.+)$", line.strip())
        if m2:
            if cur_title:
                sections.append((cur_level, cur_title, cur_lines))
            cur_level, cur_title, cur_lines = 2, m2.group(2).strip(), []
        elif m3:
            if cur_title:
                sections.append((cur_level, cur_title, cur_lines))
            cur_level, cur_title, cur_lines = 3, m3.group(2).strip(), []
        else:
            cur_lines.append(line)
    if cur_title:
        sections.append((cur_level, cur_title, cur_lines))
    if not sections:
        return body

    hist_indices = [i for i, s in enumerate(sections) if any(a in s[1] for a in _HISTORY_SECTION_ALIASES)]
    if not hist_indices:
        return body

    facts_idx = next((i for i, s in enumerate(sections) if any(a in s[1] for a in _FACTS_SECTION_ALIASES)), None)
    if facts_idx is None:
        facts_idx = next((i for i, s in enumerate(sections) if s[0] == 2), None)
    if facts_idx is None:
        return body

    hist_blocks: list[tuple[str, list[str]]] = []
    for idx in reversed(hist_indices):
        _, h_title, h_lines = sections[idx]
        hist_blocks.insert(0, (h_title, h_lines))
        del sections[idx]
        if facts_idx > idx:
            facts_idx -= 1

    f_level, f_title, f_lines = sections[facts_idx]
    for h_title, h_lines in hist_blocks:
        f_lines.append("")
        f_lines.append(f"### {h_title}")
        f_lines.extend(h_lines)
    sections[facts_idx] = (f_level, f_title, f_lines)

    result: list[str] = []
    for level, title, content in sections:
        result.append(f"{'#' * level} {title}")
        result.extend(content)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(result)).strip()


def _normalize_narrative(body: str) -> str:
    """Normalize report heading shape and remove known LLM residue."""
    if not body:
        return body
    body = _strip_llm_references(body)
    lines = body.split("\n")
    cleaned: list[str] = []
    skip_until_next_h2 = False
    for line in lines:
        stripped = line.strip()
        h3_match = re.match(r"^#{3,}\s*(.+)$", stripped)
        if h3_match:
            title = h3_match.group(1).strip()
            title = re.sub(r"^\d+[\.\、\)]\d*[\.\、\)]?\s*", "", title)
            cleaned.append(f"### {title}")
            continue
        h2_match = re.match(r"^(#{1,2})\s+(.+)$", stripped)
        if h2_match:
            title = h2_match.group(2).strip()
            title = re.sub(r"^\d+[\.\、\)]\d*[\.\、\)]?\s*", "", title)
            if any(s in title for s in _NARRATIVE_STRIP_SECTIONS):
                skip_until_next_h2 = True
                continue
            skip_until_next_h2 = False
            cleaned.append(f"## {title}")
            continue
        if skip_until_next_h2:
            continue
        cleaned.append(line)
    result = "\n".join(cleaned)
    result = _merge_history_to_facts(result)
    result = _dedupe_report_sections(result)
    result = re.sub(r"\n{3,}", "\n\n", result)
    return result.strip()


def check_structure_invariants(narrative: str, insights: Iterable[Insight] | None = None) -> list[str]:
    """Return report-structure invariant violations."""
    if not narrative:
        return ["narrative 为空"]
    violations: list[str] = []
    lines = narrative.split("\n")
    h2 = [l for l in lines if l.startswith("## ") and not l.startswith("### ")]

    if any(re.match(r"^## \d+", l) for l in h2):
        violations.append("二级标题含数字编号")
    if any("历史趋势" in l for l in h2):
        violations.append("历史趋势为独立二级标题")

    facts_i = next((i for i, l in enumerate(lines) if any(a in l for a in _FACTS_SECTION_ALIASES)), -1)
    hist_i = next((i for i, l in enumerate(lines) if "历史趋势" in l), -1)
    next_h2_i = (
        next(
            (
                i for i, l in enumerate(lines[facts_i + 1:], facts_i + 1)
                if l.startswith("## ") and not any(a in l for a in _FACTS_SECTION_ALIASES)
            ),
            len(lines),
        )
        if facts_i >= 0 else -1
    )
    if hist_i >= 0 and not (facts_i >= 0 and facts_i < hist_i < next_h2_i):
        violations.append("历史趋势不在基本事实段内")

    if any(re.match(r"^\[\^\d+\]:", l.strip()) for l in lines):
        violations.append("有脚注定义行残留")

    if any(l.strip().startswith("**") and "参考文献" in l for l in lines):
        violations.append("有 LLM 参考文献标题残留")

    future_words = (
        "若下季度", "若明年", "若后续", "若未来", "如果未来", "如果后续",
        "待观察", "待验证", "待跟踪", "待披露", "后续观察", "后续跟踪",
        "未来观察", "未来跟踪",
    )
    for ins in insights or []:
        fc = getattr(ins, "falsifiable_condition", "") or ""
        if any(w in fc for w in future_words):
            violations.append(f"洞察'{ins.claim[:15]}'可证伪条件含未来假设词")
            break

    caps = {Verdict.REFUTED: 0.20, Verdict.UNVERIFIABLE: 0.30}
    for ins in insights or []:
        cap = caps.get(ins.verdict)
        if cap is not None and (ins.confidence or 0) > cap + 0.01:
            violations.append(f"洞察'{ins.claim[:15]}'置信度超 cap")
            break

    return violations


def repair_structure_invariants_once(
    narrative: str,
    violations: list[str] | None = None,
    insights: Iterable[Insight] | None = None,
) -> tuple[str, list[str]]:
    """Apply one deterministic structure repair pass."""
    if not narrative:
        return narrative, ["narrative 为空"]

    repaired = _normalize_narrative(narrative)
    cleaned: list[str] = []
    for line in repaired.split("\n"):
        stripped = line.strip()
        if re.match(r"^\[\^\d{1,3}\]:", stripped):
            continue
        if stripped.startswith("**") and ("参考文献" in stripped or "References" in stripped):
            continue
        cleaned.append(line)

    repaired = re.sub(r"\n{3,}", "\n\n", "\n".join(cleaned)).strip()
    remaining = check_structure_invariants(repaired, insights)
    if violations and remaining and len(remaining) > len(violations):
        return narrative, violations
    return repaired, remaining
